version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p", "rootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./backend/wp-content:/var/www/html/wp-content

  reactapp:
    build: ./frontend
    ports:
      - '3000:80'
    restart: always
    depends_on:
      - wordpress
volumes:
  db_data:
